from __future__ import annotations

import argparse
import csv
import re
from pathlib import Path
from typing import Iterable


CORE_PATTERNS = [
    r"\beconom[a-z]*\b",
    r"\bfinance\b",
    r"\bfinancial\b",
    r"\bbanking\b",
    r"\bmonetary\b",
    r"\bmacroeconom(?:ics|y)?\b",
    r"\bmicroeconom(?:ics|y)?\b",
    r"\bpolitical economy\b",
    r"\bpublic choice\b",
    r"\brisk(?: | &)insurance\b",
    r"\bregional science\b",
    r"\bindustrial (?:and )?labor relations\b",
    r"\bindustrial organization\b",
    r"\bsocial choice\b",
    r"\bpolicy modeling\b",
    r"\bekonom",
    r"\bjingji\b",
]

ADJACENT_PATTERNS = [
    r"\bhealth\b",
    r"\bmedical\b",
    r"\boncology\b",
    r"\bpharmaco",
    r"\bepidemi",
    r"\benvironment",
    r"\bpollution\b",
    r"\bsustainability\b",
    r"\benergy policy\b",
    r"\burban studies\b",
    r"\bmanagement\b",
    r"\bhistorical review\b",
    r"\bdemograph",
    r"\bpopulation\b",
    r"\bdermatology\b",
    r"\burology\b",
    r"\bcardiology\b",
    r"\bpsychiatr",
    r"\bgastroenterology\b",
    r"\bobstetrics\b",
    r"\bgynecology\b",
    r"\bvascular\b",
    r"\bradiology\b",
    r"\bcleaner production\b",
    r"\bworld development\b",
    r"\bforeign affairs\b",
    r"\bresearch policy\b",
    r"\bforecasting\b",
    r"\boperational research\b",
    r"\boperations research\b",
    r"\binterdisciplinary history\b",
    r"\bbusiness history\b",
    r"\bpolitical science\b",
    r"\bhousing studies\b",
    r"\bheliyon\b",
    r"\benergies\b",
    r"\benergy\b",
]

EXCLUDE_PATTERNS = [
    r"\bworking paper\b",
    r"\bstaff country reports?\b",
    r"\breviews online\b",
    r"\bfoxbusiness\b",
    r"\blepidopter",
    r"\bentomology\b",
    r"\bzoology\b",
    r"\btime to knit\b",
    r"\bnursing standard\b",
    r"\bfilm quarterly\b",
    r"\bnewsletter\b",
    r"\bconference proceedings\b",
    r"\bweb of conferences\b",
    r"\bconference series\b",
    r"\bdigest\b",
    r"\bbriefings\b",
    r"\bweekly\b",
    r"\bnews\b",
    r"\bcongressional research service\b",
    r"\blibrary of congress\b",
    r"\bsynfacts\b",
    r"\bbusiness inform\b",
    r"\bmultidisciplinary research\b",
    r"\babstracts\b",
    r"\bnew scientist\b",
    r"\bsight sound\b",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build a first-pass OpenAlex source registry for economics selection.")
    parser.add_argument(
        "--summary-csv",
        default="data/raw/openalex/journal_field20_metadata/source_summary.csv",
        help="Source summary CSV generated by summarize_openalex_sources.py",
    )
    parser.add_argument(
        "--manual-csv",
        default="data/raw/openalex/journal_field20_metadata/source_manual_overrides.csv",
        help="Manual source bucket overrides CSV",
    )
    parser.add_argument(
        "--out-csv",
        default="data/raw/openalex/journal_field20_metadata/source_registry.csv",
        help="Output registry CSV",
    )
    parser.add_argument(
        "--review-csv",
        default="data/raw/openalex/journal_field20_metadata/source_review_queue.csv",
        help="Output review queue CSV",
    )
    parser.add_argument(
        "--review-family-csv",
        default="data/raw/openalex/journal_field20_metadata/source_review_family_summary.csv",
        help="Output normalized-family summary CSV for unresolved sources",
    )
    parser.add_argument(
        "--min-review-count",
        type=int,
        default=100,
        help="Only include unresolved sources with at least this many works in the review queue",
    )
    return parser.parse_args()


def normalize_name(text: str) -> str:
    text = (text or "").casefold().replace("&", " and ")
    cleaned = re.sub(r"[^\w]+", " ", text, flags=re.UNICODE)
    return re.sub(r"\s+", " ", cleaned).strip()


def compile_patterns(patterns: Iterable[str]) -> list[re.Pattern[str]]:
    return [re.compile(pattern, re.IGNORECASE) for pattern in patterns]


def load_manual_overrides(path: Path) -> tuple[dict[str, dict[str, str]], dict[str, dict[str, str]]]:
    by_id: dict[str, dict[str, str]] = {}
    by_name: dict[str, dict[str, str]] = {}
    if not path.exists():
        return by_id, by_name

    with path.open(encoding="utf-8") as fh:
        header = fh.readline()
        if not header:
            return by_id, by_name
        for raw_line in fh:
            line = raw_line.rstrip("\n")
            if not line.strip():
                continue
            parts = line.split(",")
            if len(parts) < 5:
                continue
            source_id = parts[0].strip()
            source_name = ",".join(parts[1:-3]).strip()
            bucket = parts[-3].strip()
            reason = parts[-2].strip()
            notes = parts[-1].strip()
            payload = {
                "bucket": bucket,
                "reason": reason,
                "notes": notes,
            }
            if source_id:
                by_id[source_id] = payload
            if source_name:
                by_name[normalize_name(source_name)] = payload
    return by_id, by_name


COMPILED_CORE_PATTERNS = compile_patterns(CORE_PATTERNS)
COMPILED_ADJACENT_PATTERNS = compile_patterns(ADJACENT_PATTERNS)
COMPILED_EXCLUDE_PATTERNS = compile_patterns(EXCLUDE_PATTERNS)


def classify_auto(name: str) -> tuple[str, str]:
    normalized = normalize_name(name)

    for pattern in COMPILED_EXCLUDE_PATTERNS:
        if pattern.search(normalized):
            return "exclude", f"exclude_pattern:{pattern.pattern}"

    for pattern in COMPILED_ADJACENT_PATTERNS:
        if pattern.search(normalized):
            return "adjacent", f"adjacent_pattern:{pattern.pattern}"

    for pattern in COMPILED_CORE_PATTERNS:
        if pattern.search(normalized):
            return "core", f"core_pattern:{pattern.pattern}"

    return "review", "no_pattern_match"


def main() -> None:
    args = parse_args()
    summary_path = Path(args.summary_csv)
    manual_path = Path(args.manual_csv)
    out_path = Path(args.out_csv)
    review_path = Path(args.review_csv)
    review_family_path = Path(args.review_family_csv)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    review_path.parent.mkdir(parents=True, exist_ok=True)
    review_family_path.parent.mkdir(parents=True, exist_ok=True)

    overrides_by_id, overrides_by_name = load_manual_overrides(manual_path)

    registry_rows: list[dict[str, str | int]] = []
    review_rows: list[dict[str, str | int]] = []
    bucket_counts = {"core": 0, "adjacent": 0, "exclude": 0, "review": 0}
    works_counts = {"core": 0, "adjacent": 0, "exclude": 0, "review": 0}

    with summary_path.open(newline="", encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            source_id = row["source_id"]
            source_name = row["source_name"]
            works_count = int(row["works_count"])
            normalized_name = normalize_name(source_name)

            override = overrides_by_id.get(source_id) or overrides_by_name.get(normalized_name)
            if override is not None:
                final_bucket = override["bucket"]
                decision_source = "manual_override"
                decision_reason = override["reason"] or "manual override"
            else:
                final_bucket, decision_reason = classify_auto(source_name)
                decision_source = "auto_rule"

            registry_row: dict[str, str | int] = {
                **row,
                "normalized_name": normalized_name,
                "final_bucket": final_bucket,
                "decision_source": decision_source,
                "decision_reason": decision_reason,
                "manual_notes": (override or {}).get("notes", ""),
            }
            registry_rows.append(registry_row)
            bucket_counts[final_bucket] += 1
            works_counts[final_bucket] += works_count

            if final_bucket == "review" and works_count >= args.min_review_count:
                review_rows.append(registry_row)

    fieldnames = list(registry_rows[0].keys()) if registry_rows else []
    with out_path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(registry_rows)

    review_rows.sort(key=lambda row: (-int(row["works_count"]), str(row["source_name"])))
    with review_path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(review_rows)

    family_summary: dict[str, dict[str, str | int | list[str]]] = {}
    for row in review_rows:
        family_key = str(row["normalized_name"] or row["source_name"])
        if family_key not in family_summary:
            family_summary[family_key] = {
                "normalized_name": family_key,
                "source_count": 0,
                "works_count": 0,
                "representative_name": str(row["source_name"]),
                "member_names": [],
            }
        item = family_summary[family_key]
        item["source_count"] = int(item["source_count"]) + 1
        item["works_count"] = int(item["works_count"]) + int(row["works_count"])
        item["member_names"].append(str(row["source_name"]))

    family_rows: list[dict[str, str | int]] = []
    for item in family_summary.values():
        member_names = sorted(set(item["member_names"]))
        family_rows.append(
            {
                "normalized_name": item["normalized_name"],
                "source_count": item["source_count"],
                "works_count": item["works_count"],
                "representative_name": item["representative_name"],
                "member_names": " | ".join(member_names[:10]),
            }
        )

    family_rows.sort(key=lambda row: (-int(row["works_count"]), str(row["representative_name"])))
    with review_family_path.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=[
                "normalized_name",
                "source_count",
                "works_count",
                "representative_name",
                "member_names",
            ],
        )
        writer.writeheader()
        writer.writerows(family_rows)

    print(f"Wrote source registry: {out_path}")
    print(f"Wrote review queue: {review_path}")
    print(f"Wrote review family summary: {review_family_path}")
    for bucket in ("core", "adjacent", "exclude", "review"):
        print(
            f"{bucket}: sources={bucket_counts[bucket]} works={works_counts[bucket]}",
        )


if __name__ == "__main__":
    main()
